name: lost_and_found
description: A flutter application for finding lost things and persons
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_spinkit: ^4.1.2
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  geolocator: ^5.2.1
  http: ^0.12.0+4
  image_picker: 0.6.3+1
  firebase_storage: ^3.0.3
  firebase_ml_vision: ^0.9.3+8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "logo.png"
flutter:
  uses-material-design: true
  assets:
    - logo.png
    - logo2.png
    - Custom-Logos.png
    - ashok.jpg